# External gems
# See http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html for making `jekyll archives` work.
plugins:
  - jekyll-archives # Sorry, not GitHub pages friendly!
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache

exclude:
  - "/vendor/"
  - .jekyll-cache

# Timezone setting
timezone: Asia/Seoul

# Site settings
title: Yangeok
subtitle: Development Blog
email: yangwookee@gmail.com
name: Yangwook Jeong
description: Yangwook Ian Jeongs' Development Blog
baseurl: ""
url: "https://yangeok.github.io" # the base hostname & protocol for your site
cover: "/assets/header_image.jpg"
logo: "/assets/logo_round_script.png"
search: "/assets/search.png"
about: "/assets/profile-placeholder.jpg"

# Build settings
# markdown: kramdown
paginate: 10
paginate_path: "/page:num/"
inter_post_navigation: true

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: "archive"
  permalinks:
    category: "/category/:name/"
    tag: '/tag/:name/'

# Disqus comments
disqus_shortname: yangeok

# Google analytics
ga_tracking_id: "UA-125441608-1"

# Category descriptions (for archive pages)
# descriptions:
# - cat: jekyll
#   desc: "Posts describing Jekyll setup techniques."

# - cat: JAVASCRIPT
#   desc: "JAVASCRIPT"

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@Theyangeok"               # (User) Name to display in the footer link
#     url:                                  # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts

social:
  - name: Kakaotalk
    icon: xi-kakaotalk
    username: wooky92
    url: kakao:wooky92
    desc: Friend me on Kakaotalk
    share: true

  - name: Stackoverflow
    icon: xi-stack-overflow
    username: Yangeok
    url: https://stackoverflow.com/users/11663715/yangwook-jeong
    desc: Connect with me on Stackoverflow
    share: true

  - name: Hashcode
    icon: xi-hlz
    username: Yangwook Jeong
    url: https://hashcode.co.kr/users/71379/yangeok
    desc: Connect with me on Hashcode
    share: true

  - name: Slideshare
    icon: xi-slideshare
    username: YangwookJeong
    url: https://www2.slideshare.net/YangwookJeong
    desc: Connect with me on Slideshare
    share: false

  - name: GitHub
    icon: fa fa-github
    username: Yangeok
    url: https://github.com/yangeok
    desc: Fork me on GitHub
    share: false

  - name: LinkedIn
    icon: xi-linkedin-square
    username: Yangwook Jeong
    url: https://www.linkedin.com/in/yangwook-jeong-3a1a24179/
    desc: Connect with me on LinkedIn
    share: true

  - name: Instagram
    icon: fa fa-instagram
    username: wooo_kee
    url: https://instagram.com/wooo_kee
    desc: Follow me on Instagram
    share: false

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
  fb_image: '/assets/logo.png'
  fb_image_width: 612
  fb_image_height: 605
  fb_image_type: 'image/png'

  twitter_image: '/assets/logo.png'

  os_repo: 'https://github.com/Yangeok/yangeok.github.io'
  os_rcs_type: 'git'
  os_src: 'git@github.com:Yangeok/yangeok.github.io.git'
