# External gems
# See http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html for making `jekyll archives` work.
plugins:
  - jekyll-archives # Sorry, not GitHub pages friendly!
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache

exclude:
  - "/vendor/"
  - .jekyll-cache

# Timezone setting
timezone: Asia/Seoul

# Site settings
title: Yangeok
subtitle: "Dev Blog"
email: yangwookee@gmail.com
name: Yangwook Jeong
description: >
  Dev Blog
baseurl: ""
url: "http://yangeok.github.io" # the base hostname & protocol for your site
cover: "/assets/header_image.jpg"
logo: "/assets/logo_round_script.png"
search: "/assets/search.png"
about: "/assets/profile-placeholder.jpg"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: "archive"
  permalinks:
    category: "/category/:name/"
    # tag: '/tag/:name/'

# Disqus comments
disqus_shortname: yangeok

# Google analytics
ga_tracking_id: "UA-125441608-1"

# Category descriptions (for archive pages)
# descriptions:
# - cat: jekyll
#   desc: "Posts describing Jekyll setup techniques."

# - cat: JAVASCRIPT
#   desc: "JAVASCRIPT"

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@Theyangeok"               # (User) Name to display in the footer link
#     url:                                  # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts

social:
  - name: Kakaotalk
    icon: xi-kakaotalk
    username: wooky92
    url: kakao:wooky92
    desc: Friend me on Kakaotalk
    share: true

  # - name: Tistory blog
  #   icon: fa fa-tumblr
  #   username: Yangeok
  #   url: https://yangwookee.tistory.com
  #   desc: Visit my daily life
  #   share: true

  - name: Stackoverflow
    icon: xi-stack-overflow
    username: Yangeok
    url: https://stackoverflow.com/users/11663715/yangwook-jeong
    desc: Connect with me on Stackoverflow
    share: true

  - name: Hashcode
    icon: xi-hlz
    username: Yangwook Jeong
    url: https://hashcode.co.kr/users/71379/yangeok
    desc: Connect with me on Hashcode
    share: true

  # - name: Okky
  #   icon: xi-full-moon
  #   username: Yangeok
  #   url: https://okky.kr/user/info/69364
  #   desc: Connect with me on Okky
  #   share: true

  # - name: Facebook
  #   icon: facebook
  #   username: yangeok
  #   url:
  #   desc: Friend me on Facebook
  #   share: true

  - name: GitHub
    icon: fa fa-github
    username: Yangeok
    url: https://github.com/yangeok
    desc: Fork me on GitHub
    share: false

  # - name: LinkedIn
  #   icon: linkedin
  #   username:
  #   url:
  #   desc: Connect with me on LinkedIn
  #   share: true

  # - name: Google+
  #   icon: google-plus
  #   username:
  #   url:
  #   desc: Add me to your Circles
  #   share: true

  # - name: YouTube
  #   icon: youtube
  #   username:
  #   url:
  #   desc: Subscribe on YouTube
  #   share: false

  - name: Instagram
    icon: fa fa-instagram
    username: wooo_kee
    url: https://instagram.com/wooo_kee
    desc: Follow me on Instagram
    share: false
  # - name: Pinterest
  #   icon: pinterest
  #   username:
  #   url:
  #   desc: Follow me on Pinterest
  #   share: true
  # - name: SoundCloud
  #   icon: soundcloud
  #   username:
  #   url:
  #   desc: Follow me on SoundCloud
  #   share: false
  # - name: Tumblr
  #   icon: tumblr
  #   username:
  #   url:
  #   desc: Follow me on Tumblr
  #   share: false
  # - name: Steam
  #   icon: steam
  #   username:
  #   url:
  #   desc: Friend me on Steam
  #   share: false
  # - name: Dribbble
  #   icon: dribbble
  #   username:
  #   url:
  #   desc: Follow me on Dribble
  #   share: false
  # - name: Vimeo
  #   icon: vimeo-square
  #   username:
  #   url:
  #   desc: Follow me on Vimeo
  #   share: false
  # - name: Vine
  #   icon: vine
  #   username:
  #   url:
  #   desc: Follow me on Vine
  #   share: false
  # - name: Reddit
  #   icon: reddit
  #   username:
  #   url:
  #   desc: Share to Reddit
  #   share: true
  # - name: "Hacker News"
  #   icon: hacker-news
  #   username:
  #   url:
  #   desc: Share to Hacker News
  #   share: false
# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
# protocols:
#   fb_image: '/assets/logo.png'
#   fb_image_width: 612
#   fb_image_height: 605
#   fb_image_type: 'image/png'

#   twitter_image: '/assets/logo.png'

#   os_repo: 'https://github.com/yangeok/centrarium.com'
#   os_rcs_type: 'git'
#   os_src: 'git@github.com:yangeok/centrarium.com.git'
